version: '3.6'
services:

  blueiris_alerts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blueiris_alerts
    volumes:
      - ./server/.env/:/opt/blueiris_alerts/server/.env
    ports:
      - 8560:8560
    restart: unless-stopped
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

