version: '3.6'
services:

  blueisis_alerts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blueisis_alerts
    volumes:
      - ./server/.env/:/opt/blueisis_alerts/server/.env
    ports:
      - 8560:8560
